-- Remplissage de cadre_resultats depuis le classeur v6 (21/08/2026)
create table if not exists public.cadre_resultats_sauvegarde_20260831 as table public.cadre_resultats;
create table if not exists public.indicateur_sauvegarde_20260831 as table public.indicateur;
alter table public.cadre_resultats_sauvegarde_20260831 enable row level security;
alter table public.indicateur_sauvegarde_20260831 enable row level security;

update public.cadre_resultats t set
  nom = v.nom,
  reference_value = v.reference,
  unite = v.unite,
  frequence = v.frequence,
  source_donnees = v.source,
  methodologie_collecte = v.methodologie,
  responsable = v.responsable,
  prevu_2023 = v.c23, prevu_2024 = v.c24, prevu_2025 = v.c25, prevu_2026 = v.c26, prevu_2027 = v.c27,
  final_prevu = v.finale,
  realise_2023 = coalesce(v.r23, t.realise_2023),
  realise_2024 = coalesce(v.r24, t.realise_2024),
  realise_2025 = coalesce(v.r25, t.realise_2025),
  realise_2026 = coalesce(v.r26, t.realise_2026),
  updated_at = now()
from (values
  ('ODP-1', 'Ventes de produits agricoles et alimentaires par les petits exploitants', '26', '%', 'Annuelle', 'Rapport Opérateur Technique', 'Enquêtes (aléatoires) sur la production des bénéficiaires qui ont reçu une subvention', 'UNCP', 0, 5, 10, 36, 30, 66, null, 0, 0, 70),
  ('ODP-2', 'Les agriculteurs adoptent une technologie agricole améliorée (CRI, nombre)', '0', 'Nombre', 'Annuelle', 'Rapport Opérateur Technique', 'Système d''information sur les bénéficiaires', 'UNCP', 0, 6000, 36000, 30000, 18000, 300000, null, 9160, 36026, null),
  ('ODP-2F', 'Les agriculteurs adoptent une technologie agricole améliorée — Femmes (CRI, nombre)', '0', 'Nombre', 'Annuelle', 'Rapport Opérateur Technique', 'Système d''information sur les bénéficiaires', 'UNCP', 0, 6000, 36000, 30000, 18000, 150000, null, 5527, 22697, null),
  ('ODP-3', 'Augmentation du rendement de maïs à travers l’incorporation de pratiques/technologies intelligentes face au climat', '0.5', '%', 'Annuelle', 'Rapport Opérateur Technique', 'Enquête sur les bénéficiaires', 'UNCP', 0, 30, 60, 80, 100, 80, null, 20, 50, 0),
  ('ODP-4', 'Augmentation du rendement de manioc à travers l’incorporation de pratiques/technologies intelligentes face au climat', '0', '%', 'Annuelle', 'Rapport Opérateur Technique', 'Enquête sur les bénéficiaires', 'UNCP', 0, 0, 25, 40, 50, 40, null, 0, null, 0),
  ('ODP-5', 'Reduction du taux de mortalité animale au niveau  des petits exploitants cibles', '0', '%', 'Annuelle', 'Rapport Opérateur Technique', 'Enquête sur les bénéficiaires', 'UNCP', 0, 20, 30, 40, 50, 40, null, 0, null, null),
  ('ODP-6', 'Provinces ciblées ayant soumis leur plan annuel d’entretien routier au FONER (nombre)', '0', 'Nombre', 'Trimestrielle / annuelle', 'Tableau de bord PNDA, données S&E, RNA, enquêtes', 'Revue documentaire', 'UNCP / cellule S&E', null, null, null, null, null, 4, null, null, null, null),
  ('ODP-7', 'Bénéficiaires directs du projet', '0', 'Nombre', 'Trimestrielle / annuelle', 'Tableau de bord PNDA, données S&E, RNA, enquêtes,Rapport OVDA/Rapport BCC/Rapport EQUITY/Rapports des prestataires', 'Enregistrement des bénéficiaires directs', 'UNCP / cellule S&E', null, 6000, 36000, 30000, 18000, 600000, null, 9160, 36026, null),
  ('ODP-7F', 'Bénéficiaires directs du projet - Femmes', '0', 'Nombre', 'Trimestrielle / annuelle', 'Tableau de bord PNDA, données S&E, RNA, enquêtes,Rapport OVDA/Rapport BCC/Rapport EQUITY/Rapports des prestataires', 'Enregistrement des bénéficiaires directs', 'UNCP / cellule S&E', null, 3000, 18000, 15000, 9000, 300000, null, 5527, 22697, null),
  ('IR-1.1.1', 'Agriculteurs atteints avec des actifs ou des services agricoles (CRI, nombre)', '0', 'Nombre', 'Semestrielle', 'Rapport Opérateur Technique', 'Données collectées par l''OT sur bénéficiaires de subvention qui ont reçu au moins la première tranche', 'UNCP', 0, 6000, 36000, 30000, 18000, 300000, null, 9160, 36026, null),
  ('IR-1.1.1F', 'Agriculteurs atteints avec des actifs ou des services agricoles — Femmes (CRI, nombre)', '0', 'Nombre', 'Semestrielle', 'Rapport Opérateur Technique', 'Données collectées par l''OT sur bénéficiaires de subvention qui ont reçu au moins la première tranche', 'UNCP', 0, 3000, 18000, 15000, 9000, 150000, null, 5527, 22697, null),
  ('IR-1.1.2', 'Fournisseurs d’intrants et de services agricoles proposant des technologies agricoles intelligente face au climat et/ou nutrition (nombre)', '4', 'Nombre', 'Semestrielle', 'Rapport Opérateur Technique', 'Données collectées par l’OT sur les prestataires prives d''intrants et services qui sont sur le registre de subvention du PNDA', 'UNCP', 4, 8, 10, 15, 20, 25, 4, 16, 29, null),
  ('IR-1.1.3', 'Petits exploitants agricoles inscrits au registre national d’agriculteurs (RNA) (nombre)', '0', 'Nombre', 'Semestrielle', 'Registre National des Agriculteurs (RNA)', 'Système d''information sur les bénéficiaires', 'UNCP', 0, 6000, 36000, 30000, 18000, 300000, 0, 9675, 65615, null),
  ('IR-1.1.3F', 'Petits exploitants agricoles inscrits au registre national d’agriculteurs (RNA) - Femmes (nombre)', '0', 'Nombre', 'Semestrielle', 'Registre National des Agriculteurs (RNA)', 'Système d''information sur les bénéficiaires', 'UNCP', 0, 3000, 18000, 15000, 9000, 150000, 0, 5620, 40026, null),
  ('IR-1.1.4', 'Superficie sous pratiques agricoles intelligentes face au climat dans les provinces ciblées (hectare)', '0', 'Ha', 'Annuelle', 'Registre National des Agriculteurs', 'RNA', 'UNCP', 0, 3000, 18000, 15000, 9000, 150000, 0, 4580, 18013, null),
  ('IR-1.1.5', 'Paquets techniques AIC/AIN proposés dans la zone du projet', '0', 'Nombre', 'Annuelle', '', '', 'UNCP', null, null, null, null, null, 4, null, null, null, null),
  ('IR-2.1.1', 'Routes réhabilitées (CRI , kilomètres)', '0', 'Km', 'Annuelle', 'Rapport OVDA', 'Système d''information de l''OVDA', 'OVDA/UNCP', 0, 0, 60, 360, 300, 400, null, 0, 0, null),
  ('IR-2.1.2', 'Nombre de CLER fonctionnel', '0', 'Nombre', 'Annuelle', 'Rapport OVDA', 'Système d''information de l''OVDA', 'OVDA/UNCP', 0, 0, 8, 15, 22, 16, null, 0, 0, null),
  ('IR-2.1.3', 'Provinces ciblées ayant soumis leur plan annuel d’entretien routier au FONER (nombre)', '0', 'Nombre', 'Trimestrielle / annuelle', 'Tableau de bord PNDA, données S&E, RNA, enquêtes', 'Revue documentaire', 'UNCP / cellule S&E', null, null, null, null, null, 4, null, null, null, null),
  ('IR-2.1.4', 'Superficie équipée en infrastructure d''irrigation', '0', 'Ha', 'Annuelle', '', '', 'UNCP', null, null, null, null, null, 300, null, null, null, null),
  ('IR-2.2.1', 'Nombre de PME ayant un prêt ou une marge de crédit (CRI, nombre)', '0', 'Nombre', 'Annuelle', 'Rapport du FGC', 'Compte du FGC', 'Gestionnaire du FGC', 0, 10, 30, 70, 100, 50, null, 0, 0, null),
  ('IR-2.2.1F', 'Nombre de PME ayant un prêt ou une marge de crédit — % dirigé par des femmes', '0', '%', 'Annuelle', '', '', 'UNCP', null, null, null, null, null, 50, null, null, null, null),
  ('IR-2.2.2', 'Nombre de personnes avec les polices de meso assurance (CRI, nombre)', '0', 'Nombre', 'Annuelle', '', '', 'UNCP', 0, 6000, 36000, 30000, 18000, 300000, null, 0, 37645, null),
  ('IR-2.2.2F', 'Nombre de personnes avec les polices de meso assurance — Femmes (CRI, nombre)', '0', 'Nombre', 'Annuelle', 'Rapport Opérateur Technique', 'Données collectées par l’Opérateur technique sur les bénéficiaires de micro assurance', 'UNCP', null, null, null, null, null, 150000, null, null, null, null),
  ('IR-2.2.3', 'Plans d''affaires mis en œuvre par les agromultiplicateurs et organisations d''agriculteurs', '0', 'Nombre', 'Annuelle', '', '', 'UNCP', null, 50, 100, 200, 300, 200, null, 0, 0, null),
  ('IR-2.2.4', 'Volume de prêts au moyen de lignes de crédit accordées par le programme aux provinces ciblées (montant USD)', '0', 'USD', 'Annuel', 'Rapport BCC sur la ligne de crédit', 'BCC Système de gestion des crédits aux IFP', 'BCC/UNCP', 0, 0, 1.2e+06, 900000, 1.2e+06, 4e+06, null, 0, 0, null),
  ('IR-2.2.5', 'Bénéficiaires atteints par les services financiers (CRI, nombre)', '0', 'Nombre', 'Annuelle', '', '', 'UNCP', 0, 6000, 36000, 30000, 18000, 300000, null, 0, 0, null),
  ('IR-2.2.5F', 'Bénéficiaires atteints par les services financiers - Femmes (CRI, nombre)', '0', 'Nombre', 'Semestrielle', 'Rapport BCC', 'Comptes de BCC et UNCP', 'Gestionnaire du BCC/UNCP', null, 3000, 18000, 15000, 9000, 150000, null, 0, 0, null),
  ('IR-2.2.6', 'Bénéficiaires ayant reçu une éducation financière (nombre)', '0', 'Nombre', 'Annuelle', '', '', 'UNCP', null, null, null, null, null, 100000, null, null, null, null),
  ('IR-3.1.1', 'Campagnes de vaccination animale dans les provinces ciblées (nombre)', '0', 'Nombre', 'Annuelle', '', '', 'UNCP', 0, 0, 1, 2, 1, 2, null, 0, 0, null),
  ('IR-3.1.2', 'Traitement des réclamations du Service de réparation des griefs dans les délais requis (GRM ) (%)', '0', '%', 'Annuelle', 'Rapport RNA', 'Système d''information du RNA', 'RNA/UNCP', 0, 100, 100, 100, 100, 100, null, 100, 100, null),
  ('IR-3.1.3', 'Cas d’exploitation et d’abus sexuels/de harcèlement sexuel traité au service (%)', '0', '%', 'Semestrielle', 'Rapports OT/UNCP/UPEP sur les GRM', 'GRM Système d''information', 'OT/UNCP/UPEP', 100, 100, 100, 100, 100, 100, null, 100, 100, null),
  ('IR-3.1.4', 'Programmes de R&D agricole sur l’AIC et l’AIN (nombre)', '0', 'Nombre', 'Annuelle', 'Rapports Opérateur Technique', 'Rapport Direction de la Sante Animale du Ministère de l''Agriculture', 'UNCP', 0, 3, 8, 18, 28, 7, null, 0, 0, null),
  ('IR-3.1.5', 'Opérationnalisation du registre national d’agriculteurs (Oui/Non)', '0', 'Oui/Non', 'Annuelle', 'Rapports Opérateur Technique et INERA', 'Rapport INERA et visite sur le terrain par l''OT', 'INERA/UNCP', 1, 1, 1, 1, 1, 1, 1, 1, 1, null),
  ('IR-3.1.6', 'Part des exploitants appuyés se déclarant satisfaits des paquets techniques reçus (%)', '0', '%', 'Annuelle', 'Rapports OT/UNCP/UPEP sur les GRM', 'Données collectées par l''OT/UNCP/UPEP', 'OT/UNCP/UPEP', 0, 70, 70, 70, 70, 70, null, 0, 0, null),
  ('IR-4.1', 'Plans de contingence pour les risques liés au secteur agricole (y compris le COVID-19) (nombre)', '0', 'Nombre', 'Annuelle', 'Rapport du Programme', 'Rapport d''activités du Programme', 'UNCP', 2, 2, 2, 2, 2, 6, 1, null, null, null)
) as v(code, nom, reference, unite, frequence, source, methodologie, responsable,
       c23,c24,c25,c26,c27, finale, r23,r24,r25,r26)
where t.code = v.code;

update public.indicateur t set
  nom_indicateur = v.nom,
  description = v.description,
  unite_mesure = v.unite,
  frequence = v.frequence,
  source_donnees = v.source,
  methodologie_collecte = v.methodologie,
  responsable_collecte = v.responsable,
  cible_2023 = v.c23, cible_2024 = v.c24, cible_2025 = v.c25, cible_2026 = v.c26, cible_2027 = v.c27,
  realise_2023 = coalesce(v.r23, t.realise_2023),
  realise_2024 = coalesce(v.r24, t.realise_2024),
  realise_2025 = coalesce(v.r25, t.realise_2025),
  realise_2026 = coalesce(v.r26, t.realise_2026),
  updated_at = now()
from (values
  ('IODP1.1', 'Ventes des petits exploitants', 'Ventes de produits agricoles et alimentaires par les petits exploitants', '%', 'annuelle', 'Rapport Opérateur Technique', 'Enquêtes (aléatoires) sur la production des bénéficiaires qui ont reçu une subvention', 'UNCP', 0, 5, 10, 36, 30, null, 0, 0, 70),
  ('IODP2.1', 'Adoption de technologies améliorées', 'Les agriculteurs adoptent une technologie agricole améliorée (CRI, nombre)', 'nombre', 'annuelle', 'Rapport Opérateur Technique', 'Système d''information sur les bénéficiaires', 'UNCP', 0, 6000, 36000, 30000, 18000, null, 9160, 36026, null),
  ('IODP2.2', 'Adoption de technologies améliorées — Femmes', 'Les agriculteurs adoptent une technologie agricole améliorée — Femmes (CRI, nombre)', 'nombre', 'annuelle', 'Rapport Opérateur Technique', 'Système d''information sur les bénéficiaires', 'UNCP', 0, 6000, 36000, 30000, 18000, null, 5527, 22697, null),
  ('IODP3.1', 'Rendement du maïs (pratiques AIC)', 'Augmentation du rendement de maïs à travers l’incorporation de pratiques/technologies intelligentes face au climat', '%', 'annuelle', 'Rapport Opérateur Technique', 'Enquête sur les bénéficiaires', 'UNCP', 0, 30, 60, 80, 100, null, 20, 50, 0),
  ('IODP3.2', 'Rendement du manioc (pratiques AIC)', 'Augmentation du rendement de manioc à travers l’incorporation de pratiques/technologies intelligentes face au climat', '%', 'annuelle', 'Rapport Opérateur Technique', 'Enquête sur les bénéficiaires', 'UNCP', 0, 0, 25, 40, 50, null, 0, null, 0),
  ('IODP3.3', 'Mortalité animale (réduction)', 'Reduction du taux de mortalité animale au niveau  des petits exploitants cibles', '%', 'annuelle', 'Rapport Opérateur Technique', 'Enquête sur les bénéficiaires', 'UNCP', 0, 20, 30, 40, 50, null, 0, null, null),
  ('IODP4.1', 'Provinces soumettant un plan FONER', 'Provinces ciblées ayant soumis leur plan annuel d’entretien routier au FONER (nombre)', 'nombre', 'trimestrielle', 'Tableau de bord PNDA, données S&E, RNA, enquêtes', 'Revue documentaire', 'UNCP / cellule S&E', null, null, null, null, null, null, null, null, null),
  ('IODP5.1', 'Bénéficiaires directs du projet', 'Bénéficiaires directs du projet', 'nombre', 'trimestrielle', 'Tableau de bord PNDA, données S&E, RNA, enquêtes,Rapport OVDA/Rapport BCC/Rapport EQUITY/Rapports des prestataires', 'Enregistrement des bénéficiaires directs', 'UNCP / cellule S&E', null, 6000, 36000, 30000, 18000, null, 9160, 36026, null),
  ('IODP5.2', 'Bénéficiaires directs — Femmes', 'Bénéficiaires directs du projet - Femmes', 'nombre', 'trimestrielle', 'Tableau de bord PNDA, données S&E, RNA, enquêtes,Rapport OVDA/Rapport BCC/Rapport EQUITY/Rapports des prestataires', 'Enregistrement des bénéficiaires directs', 'UNCP / cellule S&E', null, 3000, 18000, 15000, 9000, null, 5527, 22697, null),
  ('IR1.1.1', 'Agriculteurs atteints (actifs ou services)', 'Agriculteurs atteints avec des actifs ou des services agricoles (CRI, nombre)', 'nombre', 'semestrielle', 'Rapport Opérateur Technique', 'Données collectées par l''OT sur bénéficiaires de subvention qui ont reçu au moins la première tranche', 'UNCP', 0, 6000, 36000, 30000, 18000, null, 9160, 36026, null),
  ('IR1.1.2', 'Agriculteurs atteints — Femmes', 'Agriculteurs atteints avec des actifs ou des services agricoles — Femmes (CRI, nombre)', 'nombre', 'semestrielle', 'Rapport Opérateur Technique', 'Données collectées par l''OT sur bénéficiaires de subvention qui ont reçu au moins la première tranche', 'UNCP', 0, 3000, 18000, 15000, 9000, null, 5527, 22697, null),
  ('IR1.1.3', 'Fournisseurs d’intrants proposant l’AIC/AIN', 'Fournisseurs d’intrants et de services agricoles proposant des technologies agricoles intelligente face au climat et/ou nutrition (nombre)', 'nombre', 'semestrielle', 'Rapport Opérateur Technique', 'Données collectées par l’OT sur les prestataires prives d''intrants et services qui sont sur le registre de subvention du PNDA', 'UNCP', 4, 8, 10, 15, 20, 4, 16, 29, null),
  ('IR1.1.4', 'Exploitants inscrits au RNA', 'Petits exploitants agricoles inscrits au registre national d’agriculteurs (RNA) (nombre)', 'nombre', 'semestrielle', 'Registre National des Agriculteurs (RNA)', 'Système d''information sur les bénéficiaires', 'UNCP', 0, 6000, 36000, 30000, 18000, 0, 9675, 65615, null),
  ('IR1.1.5', 'Exploitants inscrits au RNA — Femmes', 'Petits exploitants agricoles inscrits au registre national d’agriculteurs (RNA) - Femmes (nombre)', 'nombre', 'semestrielle', 'Registre National des Agriculteurs (RNA)', 'Système d''information sur les bénéficiaires', 'UNCP', 0, 3000, 18000, 15000, 9000, 0, 5620, 40026, null),
  ('IR1.1.6', 'Superficie sous pratiques AIC', 'Superficie sous pratiques agricoles intelligentes face au climat dans les provinces ciblées (hectare)', 'ha', 'annuelle', 'Registre National des Agriculteurs', 'RNA', 'UNCP', 0, 3000, 18000, 15000, 9000, 0, 4580, 18013, null),
  ('IR2.1.1', 'Routes agricoles réhabilitées', 'Routes réhabilitées (CRI , kilomètres)', 'km', 'annuelle', 'Rapport OVDA', 'Système d''information de l''OVDA', 'OVDA/UNCP', 0, 0, 60, 360, 300, null, 0, 0, null),
  ('IR2.1.2', 'CLER fonctionnels', 'Nombre de CLER fonctionnel', 'nombre', 'annuelle', 'Rapport OVDA', 'Système d''information de l''OVDA', 'OVDA/UNCP', 0, 0, 8, 15, 22, null, 0, 0, null),
  ('IR2.1.3', 'Provinces soumettant un plan FONER', 'Provinces ciblées ayant soumis leur plan annuel d’entretien routier au FONER (nombre)', 'nombre', 'trimestrielle', 'Tableau de bord PNDA, données S&E, RNA, enquêtes', 'Revue documentaire', 'UNCP / cellule S&E', null, null, null, null, null, null, null, null, null),
  ('IR2.1.4', 'Superficie équipée en irrigation', 'Superficie équipée en infrastructure d''irrigation', 'ha', 'annuelle', '', '', 'UNCP', null, null, null, null, null, null, null, null, null),
  ('IR2.2.1', 'PME ayant un prêt ou une marge de crédit', 'Nombre de PME ayant un prêt ou une marge de crédit (CRI, nombre)', 'nombre', 'annuelle', 'Rapport du FGC', 'Compte du FGC', 'Gestionnaire du FGC', 0, 10, 30, 70, 100, null, 0, 0, null),
  ('IR2.2.2', 'PME dirigées par des femmes (part)', 'Nombre de PME ayant un prêt ou une marge de crédit — % dirigé par des femmes', '%', 'annuelle', '', '', 'UNCP', null, null, null, null, null, null, null, null, null),
  ('IR2.2.3', 'Personnes couvertes en méso-assurance', 'Nombre de personnes avec les polices de meso assurance (CRI, nombre)', 'nombre', 'annuelle', '', '', 'UNCP', 0, 6000, 36000, 30000, 18000, null, 0, 37645, null),
  ('IR2.2.4', 'Personnes couvertes en méso-assurance — Femmes', 'Nombre de personnes avec les polices de meso assurance — Femmes (CRI, nombre)', 'nombre', 'annuelle', 'Rapport Opérateur Technique', 'Données collectées par l’Opérateur technique sur les bénéficiaires de micro assurance', 'UNCP', null, null, null, null, null, null, null, null, null),
  ('IR2.2.5', 'Plans d’affaires mis en œuvre', 'Plans d''affaires mis en œuvre par les agromultiplicateurs et organisations d''agriculteurs', 'nombre', 'annuelle', '', '', 'UNCP', null, 50, 100, 200, 300, null, 0, 0, null),
  ('IR2.2.6', 'Volume de prêts sur ligne de crédit', 'Volume de prêts au moyen de lignes de crédit accordées par le programme aux provinces ciblées (montant USD)', 'usd', 'annuelle', 'Rapport BCC sur la ligne de crédit', 'BCC Système de gestion des crédits aux IFP', 'BCC/UNCP', 0, 0, 1.2e+06, 900000, 1.2e+06, null, 0, 0, null),
  ('IR3.1.1', 'Campagnes de vaccination animale', 'Campagnes de vaccination animale dans les provinces ciblées (nombre)', 'nombre', 'annuelle', '', '', 'UNCP', 0, 0, 1, 2, 1, null, 0, 0, null),
  ('IR3.1.2', 'Réclamations GRM traitées dans les délais', 'Traitement des réclamations du Service de réparation des griefs dans les délais requis (GRM ) (%)', '%', 'annuelle', 'Rapport RNA', 'Système d''information du RNA', 'RNA/UNCP', 0, 100, 100, 100, 100, null, 100, 100, null),
  ('IR3.1.3', 'Cas EAS/HS traités', 'Cas d’exploitation et d’abus sexuels/de harcèlement sexuel traité au service (%)', '%', 'semestrielle', 'Rapports OT/UNCP/UPEP sur les GRM', 'GRM Système d''information', 'OT/UNCP/UPEP', 100, 100, 100, 100, 100, null, 100, 100, null),
  ('IR4.1.1', 'Plans de contingence approuvés', 'Plans de contingence pour les risques liés au secteur agricole (y compris le COVID-19) (nombre)', 'nombre', 'annuelle', 'Rapport du Programme', 'Rapport d''activités du Programme', 'UNCP', 2, 2, 2, 2, 2, 1, null, null, null),
  ('IR1.1.7', 'Paquets techniques AIC/AIN proposés', 'Paquets techniques AIC/AIN proposés dans la zone du projet', 'nombre', 'annuelle', '', '', 'UNCP', null, null, null, null, null, null, null, null, null),
  ('IR2.2.7', 'Bénéficiaires des services financiers', 'Bénéficiaires atteints par les services financiers (CRI, nombre)', 'nombre', 'annuelle', '', '', 'UNCP', 0, 6000, 36000, 30000, 18000, null, 0, 0, null),
  ('IR2.2.8', 'Bénéficiaires des services financiers — Femmes', 'Bénéficiaires atteints par les services financiers - Femmes (CRI, nombre)', 'nombre', 'semestrielle', 'Rapport BCC', 'Comptes de BCC et UNCP', 'Gestionnaire du BCC/UNCP', null, 3000, 18000, 15000, 9000, null, 0, 0, null),
  ('IR2.2.9', 'Bénéficiaires formés en éducation financière', 'Bénéficiaires ayant reçu une éducation financière (nombre)', 'nombre', 'annuelle', '', '', 'UNCP', null, null, null, null, null, null, null, null, null),
  ('IR3.1.4', 'Programmes de R&D sur l’AIC et l’AIN', 'Programmes de R&D agricole sur l’AIC et l’AIN (nombre)', 'nombre', 'annuelle', 'Rapports Opérateur Technique', 'Rapport Direction de la Sante Animale du Ministère de l''Agriculture', 'UNCP', 0, 3, 8, 18, 28, null, 0, 0, null),
  ('IR3.1.5', 'Opérationnalisation du RNA', 'Opérationnalisation du registre national d’agriculteurs (Oui/Non)', 'oui/non', 'annuelle', 'Rapports Opérateur Technique et INERA', 'Rapport INERA et visite sur le terrain par l''OT', 'INERA/UNCP', 1, 1, 1, 1, 1, 1, 1, 1, null),
  ('IR3.1.6', 'Satisfaction des exploitants appuyés', 'Part des exploitants appuyés se déclarant satisfaits des paquets techniques reçus (%)', '%', 'annuelle', 'Rapports OT/UNCP/UPEP sur les GRM', 'Données collectées par l''OT/UNCP/UPEP', 'OT/UNCP/UPEP', 0, 70, 70, 70, 70, null, 0, 0, null)
) as v(code, nom, description, unite, frequence, source, methodologie, responsable,
       c23,c24,c25,c26,c27, r23,r24,r25,r26)
where t.code_indicateur = v.code;
